export const TIME_SLOT_OPTIONS = [
  "7am-8am",
  "8am-9am",
  "9am-10am",
  "10am-11am",
  "11am-12pm",
  "12pm-1pm",
  "1pm-2pm",
  "2pm-3pm",
  "3pm-4pm",
  "4pm-5pm",
  "5pm-6pm",
  "6pm-7pm",
  "7pm-8pm",
  "8pm-9pm",
  "9pm-10pm",
];

export const CITY_OPTIONS = ["Bangalore"];

export const BANGALORE_AREAS = [
  "Bellandur",
  "HSR Layout",
  "Kasavanahalli",
  "Kaikondrahalli",
  "Haralur",
  "Sarjapur Road",
  "Iblur",
  "Devarabisanahalli",
  "Marathahalli",
  "Kadubeesanahalli",
  "Panathur",
  "Balagere",
  "Varthur",
  "Carmelaram",
  "Doddakannelli",
  "Choodasandra",
  "Gunjur",
  "Munnekollal",
  "Brookefield",
  "Koramangala",
  "BTM Layout",
  "Bommanahalli",
  "Madiwala",
  "JP Nagar",
  "Jayanagar",
  "Bannerghatta Road",
  "Tavarekere",
  "Wilson Garden",
  "Adugodi",
  "Electronic City Phase 1",
  "Electronic City Phase 2",
  "Singasandra",
  "Begur",
  "Akshayanagar",
  "Hongasandra",
  "Whitefield",
  "KR Puram",
  "Mahadevapura",
  "Hoodi",
  "Kadugodi",
  "Indiranagar",
  "CV Raman Nagar",
  "Kaggadasapura",
  "Domlur",
  "Old Airport Road",
  "MG Road",
  "Richmond Town",
  "Shanti Nagar",
  "Ulsoor",
  "Frazer Town",
  "Cox Town",
  "Hebbal",
  "RT Nagar",
  "Yelahanka",
  "Thanisandra",
  "Hennur",
  "Rajajinagar",
  "Malleshwaram",
  "Vijayanagar",
  "Nagarbhavi",
  "Basaveshwaranagar",
  "Yeshwanthpur",
  "Jalahalli",
];

export const CUISINE_OPTIONS = [
  "North Indian",
  "South Indian",
  "East Indian",
  "West Indian",
  "Bengali",
  "Bihari",
  "Rajasthani",
  "Gujarati",
  "Maharashtrian",
  "Punjabi",
  "Sindhi",
  "Kashmiri",
  "Mughlai",
  "Jain Food",
  "Satvik Food",
  "Home-style Indian",
  "Tiffin Meals",
  "Chinese",
  "Indo-Chinese",
  "Continental",
  "Snacks / Breakfast",
  "Bakery / Desserts",
];

export const VEG_PREFERENCE_OPTIONS = [
  { label: "All", value: "all" },
  { label: "Vegetarian", value: "veg" },
  { label: "Can Cook Non-Veg", value: "nonveg" },
];
